"""modelo de datos inicial (8 tablas)

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 05:16:11.163070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docente')),
    sa.UniqueConstraint('correo', name=op.f('uq_docente_correo'))
    )
    op.create_table('proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('curso', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('url_publica', sa.String(length=500), nullable=False),
    sa.Column('elemento_verificar', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name=op.f('ck_proyecto_fechas_validas')),
    sa.CheckConstraint('length(btrim(nombre)) > 0', name=op.f('ck_proyecto_nombre_no_vacio')),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], name=op.f('fk_proyecto_docente_id_docente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proyecto'))
    )
    op.create_table('fuente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('referencia', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default=sa.text("'sin_verificar'"), nullable=False),
    sa.Column('ultima_sincronizacion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('sin_verificar', 'ok', 'fallo')", name=op.f('ck_fuente_estado_valido')),
    sa.CheckConstraint("tipo IN ('github', 'notion', 'drive')", name=op.f('ck_fuente_tipo_valido')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_fuente_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuente')),
    sa.UniqueConstraint('proyecto_id', 'tipo', name=op.f('uq_fuente_proyecto_id_tipo'))
    )
    op.create_table('indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('i1_pct_completadas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('i2_pct_pendientes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('i3_tareas_vencidas', sa.Integer(), nullable=False),
    sa.Column('i4_dias_sin_actividad', sa.Integer(), nullable=True),
    sa.Column('calculado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('i1_pct_completadas BETWEEN 0 AND 100', name=op.f('ck_indicador_i1_porcentaje')),
    sa.CheckConstraint('i2_pct_pendientes BETWEEN 0 AND 100', name=op.f('ck_indicador_i2_porcentaje')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_indicador_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicador')),
    sa.UniqueConstraint('proyecto_id', 'fecha_corte', name=op.f('uq_indicador_proyecto_id_fecha_corte'))
    )
    op.create_table('integrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_integrante_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrante'))
    )
    op.create_table('validacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(length=4), nullable=False),
    sa.Column('duracion_ms', sa.Integer(), nullable=False),
    sa.Column('ejecutada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id_actions', sa.BigInteger(), nullable=False),
    sa.Column('captura_url', sa.String(length=500), nullable=True),
    sa.CheckConstraint("resultado IN ('PASS', 'FAIL')", name=op.f('ck_validacion_resultado_valido')),
    sa.CheckConstraint('duracion_ms >= 0', name=op.f('ck_validacion_duracion_valida')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_validacion_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validacion'))
    )
    op.create_index('ix_validacion_proyecto_id_ejecutada_en', 'validacion', ['proyecto_id', 'ejecutada_en'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=150), nullable=True),
    sa.CheckConstraint("estado IS NULL OR estado IN ('Sin empezar', 'En curso', 'Listo')", name=op.f('ck_evidencia_estado_valido')),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuente.id'], name=op.f('fk_evidencia_fuente_id_fuente'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_evidencia_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidencia')),
    sa.UniqueConstraint('fuente_id', 'id_externo', name=op.f('uq_evidencia_fuente_id_id_externo'))
    )
    op.create_index('ix_evidencia_proyecto_id_fecha', 'evidencia', ['proyecto_id', 'fecha'], unique=False)
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('evidencia_id', sa.Integer(), nullable=False),
    sa.Column('regla', sa.String(length=2), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('explicacion', sa.Text(), nullable=False),
    sa.Column('origen_explicacion', sa.String(length=10), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origen_explicacion IN ('gemini', 'plantilla')", name=op.f('ck_alerta_origen_valido')),
    sa.CheckConstraint("regla IN ('R1', 'R2', 'R3', 'R4')", name=op.f('ck_alerta_regla_valida')),
    sa.ForeignKeyConstraint(['evidencia_id'], ['evidencia.id'], name=op.f('fk_alerta_evidencia_id_evidencia')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyecto.id'], name=op.f('fk_alerta_proyecto_id_proyecto'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta')),
    sa.UniqueConstraint('proyecto_id', 'fecha_corte', 'regla', 'evidencia_id', name=op.f('uq_alerta_proyecto_id_fecha_corte_regla_evidencia_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerta')
    op.drop_index('ix_evidencia_proyecto_id_fecha', table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index('ix_validacion_proyecto_id_ejecutada_en', table_name='validacion')
    op.drop_table('validacion')
    op.drop_table('integrante')
    op.drop_table('indicador')
    op.drop_table('fuente')
    op.drop_table('proyecto')
    op.drop_table('docente')
    # ### end Alembic commands ###
